/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    BadgeMedia: typeof import('./src/components/ui/BadgeMedia.vue')['default']
    BottomTabBar: typeof import('./src/components/layout/ui/BottomTabBar.vue')['default']
    ButtonVue: typeof import('./src/components/ui/ButtonVue.vue')['default']
    DatePicker: typeof import('./src/components/ui/DatePicker.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconWithName: typeof import('./src/components/layout/ui/IconWithName.vue')['default']
    LottieAsset: typeof import('./src/components/ui/LottieAsset.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    ModalBase: typeof import('./src/components/ui/ModalBase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/ui/StatusBadge.vue')['default']
    TopNavBar: typeof import('./src/components/layout/ui/TopNavBar.vue')['default']
    TypeBadge: typeof import('./src/components/ui/TypeBadge.vue')['default']
  }
}
